"""Local HTTP API (Phase 7).

A dependency-free, localhost-only JSON API over the safe agent surface. It binds
to 127.0.0.1 by default so reports and config are never exposed publicly, and it
never offers a live-trading path — only Strategy Tester research operations.

The request routing lives in :func:`handle_api_request`, a pure function that
takes ``(method, path, body)`` and returns ``(status_code, payload)``. The HTTP
server is a thin wrapper around it so the routing is fully unit-testable without
opening a socket.
"""

from __future__ import annotations

import json
from http.server import BaseHTTPRequestHandler, ThreadingHTTPServer
from typing import Any
from urllib.parse import urlparse

from mt5_research_agent import __version__
from mt5_research_agent.config import load_config
from mt5_research_agent.background_runner import build_task_status_payload
from mt5_research_agent.result_store import fetch_runs, update_leaderboard_csv


SAFE_TOOLS = (
    "validate_environment",
    "locate_ea",
    "compile_ea",
    "create_smoke_task",
    "run_task",
    "run_batch",
    "get_task_status",
    "get_leaderboard",
    "parse_report",
    "explain_decision",
    "create_research_request",
    "plan_next",
    "split_validate",
    "create_ea_from_prompt",
    "improve_ea",
    "plan_optimization",
    "parse_optimization",
    "ai_status",
)


def _config_payload() -> dict[str, Any]:
    config = load_config()
    # Localhost-only; no account credentials are stored in config, but we still
    # only surface non-sensitive operational fields.
    return {
        "terminal_path_configured": bool(config.terminal_path),
        "portable_mode": config.portable_mode,
        "artifacts_dir": config.artifacts_dir,
        "results_dir": config.results_dir,
        "report_path_strategy": config.report_path_strategy,
        "max_parallel_mt5_processes": config.max_parallel_mt5_processes,
    }


def _runs_payload(limit: int = 25) -> dict[str, Any]:
    rows = fetch_runs()[:limit]
    return {
        "ok": True,
        "count": len(rows),
        "runs": [
            {
                "test_id": row["test_id"],
                "run_status": row.get("effective_run_status", row.get("run_status", "")),
                "ea": row.get("ea", ""),
                "symbol": row.get("symbol", ""),
                "timeframe": row.get("timeframe", ""),
                "pass_fail": "PASS" if row.get("effective_pass_fail", row.get("pass_fail")) else "FAIL",
                "created_at": row.get("created_at", ""),
            }
            for row in rows
        ],
    }


def _leaderboard_payload() -> dict[str, Any]:
    path = update_leaderboard_csv()
    return {"ok": True, "leaderboard_csv": str(path), **_runs_payload()}


def _list_eas() -> list[dict[str, Any]]:
    from mt5_research_agent.mt5_diagnostics import get_experts_folder_candidates

    config = load_config()
    found: dict[str, dict[str, Any]] = {}
    for root in get_experts_folder_candidates(config):
        if not root.exists():
            continue
        for path in root.rglob("*.ex5"):
            relative = path.relative_to(root).with_suffix("")
            expert_value = str(relative).replace("/", "\\")
            found.setdefault(
                path.stem,
                {"name": path.stem, "ex5": str(path), "expert_value": expert_value},
            )
        if len(found) >= 500:
            break
    return sorted(found.values(), key=lambda item: item["name"])[:500]


def _set_preview(body: dict[str, Any]) -> dict[str, Any]:
    inputs = body.get("inputs")
    if not isinstance(inputs, dict):
        inputs = {}
    lines = ["; generated by mt5_research_agent"]
    for key, value in inputs.items():
        lines.append(f"{key}={value}")
    set_text = "\n".join(lines) + "\n"
    task = {
        "ea": str(body.get("ea", "")),
        "symbol": str(body.get("symbol", "US30")),
        "timeframe": str(body.get("timeframe", "M15")),
        "period_from": str(body.get("period_from", "2024.01.01")),
        "period_to": str(body.get("period_to", "2024.02.01")),
        "deposit": float(body.get("deposit", 10000)),
        "model": str(body.get("model", "1 minute OHLC")),
        "inputs": inputs,
    }
    return {"ok": True, "set_text": set_text, "task": task}


def _optimizer_preview(body: dict[str, Any]) -> tuple[int, dict[str, Any]]:
    from mt5_research_agent.optimizer import (
        ALGORITHM_CODES,
        CRITERION_CODES,
        build_optimization_set_text,
        grid_combination_count,
        validate_optimization_payload,
    )

    spec_payload = body.get("spec")
    if not isinstance(spec_payload, dict):
        spec_payload = body
    try:
        spec = validate_optimization_payload(spec_payload)
    except Exception as exc:
        return 400, {"ok": False, "error": str(exc)}
    return 200, {
        "ok": True,
        "test_id": spec.test_id,
        "algorithm": spec.algorithm,
        "algorithm_code": ALGORITHM_CODES[spec.algorithm],
        "criterion": spec.criterion,
        "criterion_code": CRITERION_CODES[spec.criterion],
        "grid_combinations": grid_combination_count(spec),
        "set_text": build_optimization_set_text(spec),
    }


def handle_api_request(method: str, path: str, body: dict[str, Any] | None = None) -> tuple[int, dict[str, Any]]:
    body = body or {}
    route = urlparse(path).path.rstrip("/") or "/"

    # CORS preflight for the local desktop UI (served from a different localhost
    # port / the Tauri webview origin). The server only binds to localhost.
    if method == "OPTIONS":
        return 204, {}

    if method == "GET" and route == "/health":
        return 200, {"ok": True, "version": __version__, "service": "mt5_research_agent"}

    if method == "GET" and route == "/config":
        return 200, {"ok": True, "config": _config_payload()}

    if method == "GET" and route == "/tools":
        return 200, {"ok": True, "tools": list(SAFE_TOOLS)}

    if method == "GET" and route == "/ai/status":
        from mt5_research_agent.providers import load_ai_config, load_ai_usage, resolve_base_url

        ai = load_ai_config()
        usage = load_ai_usage()
        return 200, {
            "ok": True,
            "enabled": ai.enabled,
            "provider": ai.provider,
            "model": ai.model,
            "base_url": resolve_base_url(ai),
            "max_calls": ai.max_calls,
            "max_cost_usd": ai.max_cost_usd,
            "calls_used": int(usage.get("calls", 0)),
            "est_cost_usd": float(usage.get("est_cost_usd", 0.0)),
        }

    if method == "GET" and route.startswith("/optimizations/"):
        from mt5_research_agent.background_runner import configured_artifacts_dir

        test_id = route.split("/optimizations/", 1)[1]
        result_path = configured_artifacts_dir() / "optimizations" / test_id / "optimization_result.json"
        if not result_path.exists():
            return 404, {"ok": False, "error": f"No optimization result for {test_id}"}
        try:
            payload = json.loads(result_path.read_text(encoding="utf-8"))
        except (OSError, json.JSONDecodeError) as exc:
            return 500, {"ok": False, "error": str(exc)}
        return 200, {"ok": True, "optimization": payload}

    if method == "GET" and route == "/runs":
        return 200, _runs_payload()

    if method == "GET" and route == "/leaderboard":
        return 200, _leaderboard_payload()

    if method == "GET" and route.startswith("/reports/"):
        test_id = route.split("/reports/", 1)[1]
        payload = build_task_status_payload(test_id)
        return (200 if payload.get("ok") else 404), payload

    if method == "GET" and route == "/session":
        from mt5_research_agent.session import session_status

        return 200, session_status()

    if method == "GET" and route == "/mt5-process-status":
        from mt5_research_agent.mt5_process import mt5_process_status_payload

        return 200, {"ok": True, **mt5_process_status_payload(load_config())}

    if method == "POST" and route == "/session/start":
        from mt5_research_agent.session import start_session

        result = start_session(confirm=bool(body.get("confirm", False)))
        return (200 if result.get("ok") else 409), result

    if method == "POST" and route == "/session/stop":
        from mt5_research_agent.session import stop_session

        result = stop_session(confirm=bool(body.get("confirm", False)))
        return (200 if result.get("ok") else 409), result

    if method == "GET" and route == "/detect":
        from mt5_research_agent.maintenance import config_wizard_detection

        checks = config_wizard_detection(load_config())
        return 200, {
            "ok": True,
            "checks": [
                {"label": label, "status": "PASS" if ok else "WARN", "ok": ok, "detail": detail}
                for label, ok, detail in checks
            ],
        }

    if method == "GET" and route == "/eas":
        return 200, {"ok": True, "eas": _list_eas()}

    if method == "GET" and route == "/detect-terminal":
        from mt5_research_agent.maintenance import detect_terminal_path

        detected = detect_terminal_path()
        return 200, {"ok": True, "terminal_path": detected, "found": bool(detected)}

    if method == "POST" and route == "/config/save":
        from mt5_research_agent.maintenance import apply_config_updates, config_wizard_detection

        try:
            saved_path = apply_config_updates(body)
            checks = config_wizard_detection(load_config())
        except Exception as exc:
            return 400, {"ok": False, "error": str(exc)}
        return 200, {
            "ok": True,
            "config_path": str(saved_path),
            "config": _config_payload(),
            "checks": [
                {"label": label, "status": "PASS" if ok else "WARN", "ok": ok, "detail": detail}
                for label, ok, detail in checks
            ],
        }

    if method == "POST" and route == "/set-preview":
        return 200, _set_preview(body)

    if method == "POST" and route == "/optimizer/preview":
        return _optimizer_preview(body)

    if method == "GET" and route == "/jobs":
        from mt5_research_agent.jobs import get_queue, job_to_payload

        jobs = [job_to_payload(record) for record in get_queue().list()]
        return 200, {"ok": True, "jobs": jobs}

    if method == "POST" and route == "/jobs":
        from mt5_research_agent.jobs import get_queue, job_to_payload

        job_type = str(body.get("type", "")).strip()
        if not job_type:
            return 400, {"ok": False, "error": "job 'type' is required"}
        try:
            record = get_queue().submit(job_type, body.get("params") or {}, title=str(body.get("title", "")))
        except ValueError as exc:
            return 400, {"ok": False, "error": str(exc)}
        return 200, {"ok": True, "job": job_to_payload(record)}

    if method == "GET" and route.startswith("/jobs/"):
        from mt5_research_agent.jobs import get_queue, job_to_payload

        job_id = route.split("/jobs/", 1)[1]
        found = get_queue().get(job_id)
        if found is None:
            return 404, {"ok": False, "error": f"No job {job_id}"}
        return 200, {"ok": True, "job": job_to_payload(found)}

    if method == "POST" and route.startswith("/jobs/") and route.endswith("/cancel"):
        from mt5_research_agent.jobs import get_queue

        job_id = route[len("/jobs/"):-len("/cancel")]
        cancelled = get_queue().cancel(job_id)
        return (200 if cancelled else 409), {"ok": cancelled, "job_id": job_id}

    if method == "POST" and route == "/research-requests":
        request_path = body.get("request_path")
        if not request_path:
            return 400, {"ok": False, "error": "request_path is required"}
        from mt5_research_agent.research_workflow import parse_research_request

        try:
            request = parse_research_request(request_path)
        except Exception as exc:
            return 400, {"ok": False, "error": str(exc)}
        return 200, {
            "ok": not request.todos,
            "slug": request.slug,
            "ea": request.ea,
            "symbol": request.symbol,
            "timeframe": request.timeframe,
            "parameter_keys": list(request.parameter_space),
            "todos": request.todos,
        }

    if method == "POST" and route == "/planner/next":
        request_path = body.get("request_path")
        if not request_path:
            return 400, {"ok": False, "error": "request_path is required"}
        from mt5_research_agent.planner import build_next_plan
        from mt5_research_agent.research_workflow import parse_research_request

        try:
            request = parse_research_request(request_path)
            plan_path, experiment_path = build_next_plan(request)
        except Exception as exc:
            return 400, {"ok": False, "error": str(exc)}
        return 200, {"ok": True, "plan_path": str(plan_path), "experiment_path": str(experiment_path)}

    if method == "POST" and route == "/ea/create":
        prompt_path = body.get("prompt_path")
        if not prompt_path:
            return 400, {"ok": False, "error": "prompt_path is required"}
        from mt5_research_agent.ea_lab import create_ea_from_prompt

        try:
            result = create_ea_from_prompt(prompt_path)
        except Exception as exc:
            return 400, {"ok": False, "error": str(exc)}
        return 200, result

    return 404, {"ok": False, "error": f"No route for {method} {route}"}


class _Handler(BaseHTTPRequestHandler):
    server_version = "MT5ResearchAgentAPI"

    def _cors_headers(self) -> None:
        # Localhost-only server; allow the local desktop UI / Tauri webview to call it.
        self.send_header("Access-Control-Allow-Origin", "*")
        self.send_header("Access-Control-Allow-Methods", "GET, POST, OPTIONS")
        self.send_header("Access-Control-Allow-Headers", "Content-Type")

    def _respond(self, status: int, payload: dict[str, Any]) -> None:
        data = json.dumps(payload).encode("utf-8")
        self.send_response(status)
        self.send_header("Content-Type", "application/json")
        self.send_header("Content-Length", str(len(data)))
        self._cors_headers()
        self.end_headers()
        self.wfile.write(data)

    def do_OPTIONS(self) -> None:  # noqa: N802 - required name
        self.send_response(204)
        self._cors_headers()
        self.send_header("Content-Length", "0")
        self.end_headers()

    def _read_body(self) -> dict[str, Any]:
        length = int(self.headers.get("Content-Length", 0) or 0)
        if length <= 0:
            return {}
        raw = self.rfile.read(length)
        try:
            parsed = json.loads(raw.decode("utf-8"))
            return parsed if isinstance(parsed, dict) else {}
        except (UnicodeDecodeError, json.JSONDecodeError):
            return {}

    def do_GET(self) -> None:  # noqa: N802 - required name
        status, payload = handle_api_request("GET", self.path)
        self._respond(status, payload)

    def do_POST(self) -> None:  # noqa: N802 - required name
        status, payload = handle_api_request("POST", self.path, self._read_body())
        self._respond(status, payload)

    def log_message(self, *args: Any) -> None:  # silence default stderr logging
        return


def serve_api(host: str = "127.0.0.1", port: int = 8765) -> ThreadingHTTPServer:
    if host not in {"127.0.0.1", "localhost"}:
        raise ValueError("Refusing to bind the API to a non-localhost host.")
    server = ThreadingHTTPServer((host, port), _Handler)
    return server


def run_serve_api_command(host: str, port: int) -> int:
    try:
        server = serve_api(host, port)
    except Exception as exc:
        print(str(exc))
        return 1
    print(f"serving MT5 Research Agent API on http://{host}:{port}")
    print("press Ctrl+C to stop")
    try:
        server.serve_forever()
    except KeyboardInterrupt:
        print("stopping API server")
    finally:
        server.server_close()
    return 0
