"""Phase 5 EA Lab.

Create, compile, smoke-test, version, and improve MetaTrader 5 Expert Advisors.

Hard rules:
- Generated EAs default to safe behavior: one position at a time, no martingale,
  no grid, no unlimited stacking, explicit risk inputs, a session filter, and a
  spread filter. Every meaningful value is an MQL5 ``input``.
- Generated EAs never contain hidden network calls or hardcoded account
  credentials.
- A working EA version is never overwritten without keeping the previous source
  in ``versions/``. Every change records the reason and supporting evidence.
- The Lab only ever drives the Strategy Tester. It never places live orders.
"""

from __future__ import annotations

import json
import re
import shutil
from dataclasses import dataclass, field
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

from mt5_research_agent.background_runner import build_smoke_task_payload, run_task_cli
from mt5_research_agent.config import load_config
from mt5_research_agent.mt5_diagnostics import (
    compile_ea_payload,
    get_experts_folder_candidates,
)
from mt5_research_agent.task import task_to_payload, validate_task_payload


# EAs generated by the Lab live in a dedicated sandbox subfolder so we never
# touch or overwrite the user's own Experts.
LAB_EXPERTS_SUBFOLDER = "MT5ResearchAgentLab"

DEFAULT_EA_INPUTS: dict[str, str] = {
    "InpLots": "0.10",
    "InpRiskPercent": "0.0",
    "InpATRPeriod": "14",
    "InpSL_ATR_Mult": "1.5",
    "InpTP_R": "2.0",
    "InpBreakoutBars": "20",
    "InpSessionStartHour": "8",
    "InpSessionEndHour": "20",
    "InpMaxSpreadPoints": "50",
    "InpMaxPositions": "1",
    "InpAllowWednesday": "true",
    "InpMagic": "990001",
}


@dataclass(slots=True)
class EaSpec:
    name: str
    symbol: str
    timeframe: str
    strategy_note: str
    inputs: dict[str, str] = field(default_factory=dict)
    prompt: str = ""


def utc_now_iso() -> str:
    return datetime.now(timezone.utc).isoformat()


def ea_lab_root() -> Path:
    config = load_config()
    path = Path(config.artifacts_dir).resolve() / "ea_lab"
    path.mkdir(parents=True, exist_ok=True)
    return path


def ea_dir(ea_name: str) -> Path:
    return ea_lab_root() / ea_name


def ensure_ea_lab_dirs(ea_name: str) -> dict[str, Path]:
    root = ea_dir(ea_name)
    subdirs = {
        "source": root / "source",
        "compiled": root / "compiled",
        "compile_logs": root / "compile_logs",
        "smoke_tests": root / "smoke_tests",
        "research_requests": root / "research_requests",
        "improvement_history": root / "improvement_history",
        "reports": root / "reports",
        "versions": root / "versions",
    }
    for path in subdirs.values():
        path.mkdir(parents=True, exist_ok=True)
    return subdirs


def metadata_path(ea_name: str) -> Path:
    return ea_dir(ea_name) / "metadata.json"


def load_metadata(ea_name: str) -> dict[str, Any] | None:
    path = metadata_path(ea_name)
    if not path.exists():
        return None
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError):
        return None


def save_metadata(ea_name: str, metadata: dict[str, Any]) -> Path:
    ensure_ea_lab_dirs(ea_name)
    path = metadata_path(ea_name)
    path.write_text(json.dumps(metadata, indent=2), encoding="utf-8")
    return path


def slugify_ea_name(text: str) -> str:
    cleaned = re.sub(r"[^A-Za-z0-9]+", "_", text).strip("_")
    return cleaned or "GeneratedEA"


def parse_ea_prompt(prompt_path: str | Path) -> EaSpec:
    """Parse a free-text EA prompt markdown file into a structured spec.

    Recognized optional sections: ``## EA name``, ``## Symbol``,
    ``## Timeframe``. Everything else is treated as the strategy note. This is
    deterministic and local-only; it never invents account or network behavior.
    """

    source = Path(prompt_path)
    text = source.read_text(encoding="utf-8") if source.exists() else str(prompt_path)

    def section_value(name: str) -> str:
        match = re.search(
            rf"^#{{1,6}}\s*{re.escape(name)}\s*$\n(.*?)(?=^#{{1,6}}\s|\Z)",
            text,
            re.IGNORECASE | re.MULTILINE | re.DOTALL,
        )
        if not match:
            return ""
        body = match.group(1).strip()
        first = next((line.strip().lstrip("-* ").strip() for line in body.splitlines() if line.strip()), "")
        return first

    name = section_value("EA name") or (source.stem if source.exists() else "GeneratedEA")
    symbol = section_value("Symbol") or "US30"
    timeframe = section_value("Timeframe") or "M15"
    return EaSpec(
        name=slugify_ea_name(name),
        symbol=symbol,
        timeframe=timeframe,
        strategy_note=text.strip(),
        inputs=dict(DEFAULT_EA_INPUTS),
        prompt=text.strip(),
    )


EA_TEMPLATE = '''//+------------------------------------------------------------------+
//| {ea_name}_v{version}.mq5
//| Generated by MT5 Research Agent EA Lab.
//| Strategy Tester research only. No live trading is intended.
//| Safety defaults: one position max, no martingale, no grid,
//| explicit risk controls, session filter, spread filter.
//+------------------------------------------------------------------+
#property strict
#property version   "{version}.0"
#property description "Generated by MT5 Research Agent EA Lab (Strategy Tester research only)."

#include <Trade/Trade.mqh>

// All meaningful values are inputs so the research loop can tune them.
input double InpLots            = {InpLots};            // Fixed lot size (used when InpRiskPercent == 0)
input double InpRiskPercent     = {InpRiskPercent};     // Risk percent per trade (0 = use fixed lot)
input int    InpATRPeriod       = {InpATRPeriod};       // ATR period for stop sizing
input double InpSL_ATR_Mult     = {InpSL_ATR_Mult};     // Stop loss = ATR * this multiple
input double InpTP_R            = {InpTP_R};            // Take profit as a multiple of risk (R)
input int    InpBreakoutBars    = {InpBreakoutBars};    // Lookback bars for breakout high/low
input int    InpSessionStartHour= {InpSessionStartHour};// Session start hour (server time)
input int    InpSessionEndHour  = {InpSessionEndHour};  // Session end hour (server time)
input int    InpMaxSpreadPoints = {InpMaxSpreadPoints}; // Skip trades above this spread (points)
input int    InpMaxPositions    = {InpMaxPositions};    // Maximum concurrent positions (>=1)
input bool   InpAllowWednesday  = {InpAllowWednesday};  // Allow new trades on Wednesday
input long   InpMagic           = {InpMagic};           // Magic number

CTrade   trade;
int      atrHandle = INVALID_HANDLE;

//+------------------------------------------------------------------+
int OnInit()
  {{
   if(InpMaxPositions < 1)
     {{
      Print("InpMaxPositions must be >= 1; refusing unsafe stacking config.");
      return(INIT_PARAMETERS_INCORRECT);
     }}
   if(InpSL_ATR_Mult <= 0.0 || InpTP_R <= 0.0)
     {{
      Print("Stop and take-profit multiples must be positive.");
      return(INIT_PARAMETERS_INCORRECT);
     }}
   atrHandle = iATR(_Symbol, _Period, InpATRPeriod);
   if(atrHandle == INVALID_HANDLE)
     {{
      Print("Failed to create ATR handle.");
      return(INIT_FAILED);
     }}
   trade.SetExpertMagicNumber(InpMagic);
   return(INIT_SUCCEEDED);
  }}

//+------------------------------------------------------------------+
void OnDeinit(const int reason)
  {{
   if(atrHandle != INVALID_HANDLE)
      IndicatorRelease(atrHandle);
  }}

//+------------------------------------------------------------------+
int CountOwnPositions()
  {{
   int total = 0;
   for(int i = PositionsTotal() - 1; i >= 0; i--)
     {{
      ulong ticket = PositionGetTicket(i);
      if(ticket == 0)
         continue;
      if(PositionGetInteger(POSITION_MAGIC) == InpMagic &&
         PositionGetString(POSITION_SYMBOL) == _Symbol)
         total++;
     }}
   return(total);
  }}

//+------------------------------------------------------------------+
bool InSession()
  {{
   MqlDateTime now;
   TimeToStruct(TimeCurrent(), now);
   if(!InpAllowWednesday && now.day_of_week == 3)
      return(false);
   if(InpSessionStartHour <= InpSessionEndHour)
      return(now.hour >= InpSessionStartHour && now.hour < InpSessionEndHour);
   return(now.hour >= InpSessionStartHour || now.hour < InpSessionEndHour);
  }}

//+------------------------------------------------------------------+
bool SpreadOk()
  {{
   long spread = SymbolInfoInteger(_Symbol, SYMBOL_SPREAD);
   return(spread <= (long)InpMaxSpreadPoints);
  }}

//+------------------------------------------------------------------+
double LotSize(double stopDistance)
  {{
   if(InpRiskPercent <= 0.0 || stopDistance <= 0.0)
      return(InpLots);
   double balance   = AccountInfoDouble(ACCOUNT_BALANCE);
   double riskMoney = balance * (InpRiskPercent / 100.0);
   double tickValue = SymbolInfoDouble(_Symbol, SYMBOL_TRADE_TICK_VALUE);
   double tickSize  = SymbolInfoDouble(_Symbol, SYMBOL_TRADE_TICK_SIZE);
   if(tickValue <= 0.0 || tickSize <= 0.0)
      return(InpLots);
   double valuePerPoint = tickValue / tickSize;
   double lots = riskMoney / (stopDistance * valuePerPoint);
   double minLot = SymbolInfoDouble(_Symbol, SYMBOL_VOLUME_MIN);
   double step   = SymbolInfoDouble(_Symbol, SYMBOL_VOLUME_STEP);
   if(step > 0.0)
      lots = MathFloor(lots / step) * step;
   return(MathMax(minLot, lots));
  }}

//+------------------------------------------------------------------+
void OnTick()
  {{
   // One decision per new bar.
   static datetime lastBar = 0;
   datetime currentBar = iTime(_Symbol, _Period, 0);
   if(currentBar == lastBar)
      return;
   lastBar = currentBar;

   if(CountOwnPositions() >= InpMaxPositions)
      return;
   if(!InSession() || !SpreadOk())
      return;

   double atr[];
   if(CopyBuffer(atrHandle, 0, 1, 1, atr) <= 0)
      return;
   double atrValue = atr[0];
   if(atrValue <= 0.0)
      return;

   double highest = iHigh(_Symbol, _Period, iHighest(_Symbol, _Period, MODE_HIGH, InpBreakoutBars, 1));
   double lowest  = iLow(_Symbol, _Period, iLowest(_Symbol, _Period, MODE_LOW, InpBreakoutBars, 1));
   double ask = SymbolInfoDouble(_Symbol, SYMBOL_ASK);
   double bid = SymbolInfoDouble(_Symbol, SYMBOL_BID);

   double stopDistance = atrValue * InpSL_ATR_Mult;

   if(ask > highest)
     {{
      double sl = ask - stopDistance;
      double tp = ask + stopDistance * InpTP_R;
      trade.Buy(LotSize(stopDistance), _Symbol, ask, sl, tp, "lab-breakout");
     }}
   else if(bid < lowest)
     {{
      double sl = bid + stopDistance;
      double tp = bid - stopDistance * InpTP_R;
      trade.Sell(LotSize(stopDistance), _Symbol, bid, sl, tp, "lab-breakout");
     }}
  }}
//+------------------------------------------------------------------+
'''


def generate_ea_source(spec: EaSpec, version: int) -> str:
    values = {key: spec.inputs.get(key, default) for key, default in DEFAULT_EA_INPUTS.items()}
    return EA_TEMPLATE.format(ea_name=spec.name, version=version, **values)


def next_version(ea_name: str) -> int:
    metadata = load_metadata(ea_name)
    if not metadata:
        return 1
    return int(metadata.get("current_version", 0)) + 1


def _experts_lab_dir(config) -> Path | None:
    for candidate in get_experts_folder_candidates(config):
        if candidate.exists():
            target = candidate / LAB_EXPERTS_SUBFOLDER
            target.mkdir(parents=True, exist_ok=True)
            return target
    return None


def create_ea_from_prompt(prompt_path: str | Path) -> dict[str, Any]:
    spec = parse_ea_prompt(prompt_path)
    subdirs = ensure_ea_lab_dirs(spec.name)
    version = next_version(spec.name)
    source_text = generate_ea_source(spec, version)

    versioned_name = f"{spec.name}_v{version}.mq5"
    version_source_path = subdirs["versions"] / versioned_name
    version_source_path.write_text(source_text, encoding="utf-8")
    active_source_path = subdirs["source"] / f"{spec.name}.mq5"
    active_source_path.write_text(source_text, encoding="utf-8")

    config = load_config()
    experts_dir = _experts_lab_dir(config)
    experts_path = ""
    warnings: list[str] = []
    if experts_dir is not None:
        target = experts_dir / versioned_name
        target.write_text(source_text, encoding="utf-8")
        experts_path = str(target)
    else:
        warnings.append(
            "No MT5 Experts folder found; EA was written to artifacts only. "
            "Copy it into MQL5\\Experts and compile before testing."
        )

    metadata = load_metadata(spec.name) or {
        "ea_name": spec.name,
        "symbol": spec.symbol,
        "timeframe": spec.timeframe,
        "created_at": utc_now_iso(),
        "current_version": 0,
        "versions": [],
        "improvement_history": [],
    }
    metadata["symbol"] = spec.symbol
    metadata["timeframe"] = spec.timeframe
    metadata["current_version"] = version
    metadata["versions"].append(
        {
            "version": version,
            "created_at": utc_now_iso(),
            "reason": "create-ea-from-prompt",
            "version_source_path": str(version_source_path),
            "active_source_path": str(active_source_path),
            "experts_path": experts_path,
            "compile": None,
            "smoke": None,
        }
    )
    save_metadata(spec.name, metadata)

    return {
        "ok": True,
        "ea_name": spec.name,
        "version": version,
        "versioned_name": versioned_name,
        "version_source_path": str(version_source_path),
        "active_source_path": str(active_source_path),
        "experts_path": experts_path,
        "warnings": warnings,
    }


def _update_latest_version(ea_name: str, key: str, value: Any) -> None:
    metadata = load_metadata(ea_name)
    if not metadata or not metadata.get("versions"):
        return
    metadata["versions"][-1][key] = value
    save_metadata(ea_name, metadata)


def run_create_ea_from_prompt_command(prompt_path: str) -> int:
    try:
        result = create_ea_from_prompt(prompt_path)
    except Exception as exc:
        print(str(exc))
        return 1
    print(f"ea: {result['ea_name']}")
    print(f"version: v{result['version']}")
    print(f"version source: {result['version_source_path']}")
    print(f"active source: {result['active_source_path']}")
    print(f"experts copy: {result['experts_path'] or '<not copied>'}")
    for warning in result["warnings"]:
        print(f"warning: {warning}")
    print("next: compile-ea then smoke-test-ea")
    return 0


def run_ea_lab_status_command(ea_name: str) -> int:
    metadata = load_metadata(ea_name)
    if metadata is None:
        print(f"No EA Lab metadata found for: {ea_name}")
        return 1
    print(f"ea: {metadata['ea_name']}")
    print(f"symbol: {metadata.get('symbol', '')}")
    print(f"timeframe: {metadata.get('timeframe', '')}")
    print(f"current version: v{metadata.get('current_version', 0)}")
    print(f"versions: {len(metadata.get('versions', []))}")
    print(f"improvement entries: {len(metadata.get('improvement_history', []))}")
    latest = metadata.get("versions", [])[-1] if metadata.get("versions") else None
    if latest:
        compile_state = latest.get("compile")
        smoke_state = latest.get("smoke")
        print(f"latest compile: {compile_state.get('ok') if isinstance(compile_state, dict) else '<none>'}")
        print(f"latest smoke status: {smoke_state.get('status') if isinstance(smoke_state, dict) else '<none>'}")
    return 0


def run_ea_version_history_command(ea_name: str) -> int:
    metadata = load_metadata(ea_name)
    if metadata is None:
        print(f"No EA Lab metadata found for: {ea_name}")
        return 1
    versions = metadata.get("versions", [])
    if not versions:
        print("No versions recorded yet.")
        return 0
    print(f"ea: {ea_name}")
    for entry in versions:
        compile_state = entry.get("compile")
        smoke_state = entry.get("smoke")
        compile_ok = compile_state.get("ok") if isinstance(compile_state, dict) else None
        smoke_status = smoke_state.get("status") if isinstance(smoke_state, dict) else None
        print(
            f"- v{entry['version']} | {entry.get('created_at', '')} | reason={entry.get('reason', '')} "
            f"| compile_ok={compile_ok} | smoke={smoke_status}"
        )
    return 0


def revert_ea(ea_name: str, to_version: int) -> dict[str, Any]:
    metadata = load_metadata(ea_name)
    if metadata is None:
        raise ValueError(f"No EA Lab metadata found for: {ea_name}")
    target_entry = next((entry for entry in metadata.get("versions", []) if entry["version"] == to_version), None)
    if target_entry is None:
        raise ValueError(f"Version v{to_version} not found for {ea_name}.")
    version_source = Path(target_entry["version_source_path"])
    if not version_source.exists():
        raise ValueError(f"Stored source for v{to_version} is missing: {version_source}")

    subdirs = ensure_ea_lab_dirs(ea_name)
    source_text = version_source.read_text(encoding="utf-8")
    active_source_path = subdirs["source"] / f"{ea_name}.mq5"
    # Back up the current active source before overwriting.
    if active_source_path.exists():
        backup = subdirs["versions"] / f"{ea_name}_pre_revert_{datetime.now(timezone.utc).strftime('%Y%m%dT%H%M%SZ')}.mq5"
        shutil.copy2(active_source_path, backup)
    active_source_path.write_text(source_text, encoding="utf-8")

    metadata["current_version"] = to_version
    metadata.setdefault("improvement_history", []).append(
        {
            "at": utc_now_iso(),
            "action": "revert",
            "to_version": to_version,
        }
    )
    save_metadata(ea_name, metadata)
    return {"ok": True, "ea_name": ea_name, "reverted_to": to_version, "active_source_path": str(active_source_path)}


def run_revert_ea_command(ea_name: str, to_version: int) -> int:
    try:
        result = revert_ea(ea_name, to_version)
    except Exception as exc:
        print(str(exc))
        return 1
    print(f"reverted {result['ea_name']} to v{result['reverted_to']}")
    print(f"active source: {result['active_source_path']}")
    return 0


def active_versioned_ea(ea_name: str) -> str:
    metadata = load_metadata(ea_name)
    version = int(metadata.get("current_version", 1)) if metadata else 1
    return f"{ea_name}_v{version}"


def run_smoke_test_ea_command(
    ea_name: str,
    *,
    symbol: str,
    timeframe: str,
    period_from: str,
    period_to: str,
    deposit: float,
    run: bool,
    timeout_seconds: int,
) -> int:
    metadata = load_metadata(ea_name)
    if metadata is None:
        print(f"No EA Lab metadata found for: {ea_name}. Run create-ea-from-prompt first.")
        return 1

    subdirs = ensure_ea_lab_dirs(ea_name)
    versioned = active_versioned_ea(ea_name)
    version = int(metadata.get("current_version", 1))
    test_id = f"{ea_name.upper()}-V{version}-SMOKE"
    payload = build_smoke_task_payload(
        test_id=test_id,
        ea=versioned,
        symbol=symbol,
        timeframe=timeframe,
        period_from=period_from,
        period_to=period_to,
        deposit=deposit,
    )
    task = validate_task_payload(payload)
    task_path = subdirs["smoke_tests"] / f"{test_id}.json"
    task_path.write_text(json.dumps(task_to_payload(task), indent=2), encoding="utf-8")

    print(f"ea: {ea_name} ({versioned})")
    print(f"smoke task: {task_path}")
    if not run:
        print("Dry smoke complete. Re-run with --run to launch MT5 in background CLI mode.")
        return 0

    result = run_task_cli(str(task_path), timeout_seconds)
    _update_latest_version(
        ea_name,
        "smoke",
        {
            "at": utc_now_iso(),
            "test_id": result.test_id,
            "status": result.status,
            "raw_report_path": result.raw_report_path,
            "log_path": result.log_path,
        },
    )
    print(f"status: {result.status}")
    if result.raw_report_path:
        print(f"raw report: {result.raw_report_path}")
    print(f"log: {result.log_path}")
    return result.exit_code


def run_improve_ea_command(
    ea_name: str,
    *,
    goal_request: str,
    max_rounds: int,
    allow_gui_clicks: bool,
    timeout_seconds: int,
) -> int:
    metadata = load_metadata(ea_name)
    if metadata is None:
        print(f"No EA Lab metadata found for: {ea_name}. Run create-ea-from-prompt first.")
        return 1

    # Parameter search comes before any code change (per EA Lab improvement
    # rules). Code mutation is intentionally not automated here; the loop tunes
    # inputs and reports honestly whether the goal was reached.
    from mt5_research_agent.goal_seeker import run_goal_seek

    try:
        result = run_goal_seek(
            goal_request,
            max_rounds=max_rounds,
            allow_gui_clicks=allow_gui_clicks,
            timeout_seconds=timeout_seconds,
        )
    except Exception as exc:
        print(str(exc))
        return 1

    metadata.setdefault("improvement_history", []).append(
        {
            "at": utc_now_iso(),
            "action": "parameter_search",
            "goal_request": goal_request,
            "target_reached": result.target_reached,
            "best_robust_id": result.best_robust_id,
            "closest_raw_id": result.closest_raw_id,
            "report_path": result.report_path,
            "stop_reason": result.stop_reason,
        }
    )
    save_metadata(ea_name, metadata)

    print(f"ea: {ea_name}")
    print(f"target reached: {result.target_reached}")
    print(f"stop reason: {result.stop_reason}")
    print(f"final report: {result.report_path}")
    print("note: parameter search only; source-code mutation is not automated in this phase.")
    return 0


def run_compile_ea_lab_command(ea_name: str) -> int:
    """Compile the current EA version through MetaEditor and store the result."""

    payload = compile_ea_payload(ea_name)
    _update_latest_version(
        ea_name,
        "compile",
        {"ok": bool(payload.get("ok")), "at": utc_now_iso(), "compile_log_path": payload.get("compile_log_path", "")},
    )
    print(f"ea: {ea_name}")
    print(f"compile ok: {payload.get('ok')}")
    for warning in payload.get("warnings", []):
        print(f"warning: {warning}")
    return 0 if payload.get("ok") else 1
